### ISSUE TITLE
Enable GitHub discussions

### ISSUE THREAD

**Issue by remote-gildor** [TCGV/DeFiOptions#1]
Hi Thomas, cool project! 🙂  I suggest enabling GitHub Discussions (Settings > Features > Enable Discussions), so that it's easier to discuss different proposals, ideas etc. (anything that's not an issue): https://docs.github.com/en/discussions/quickstart 

Best,
Gildor

**Comment by TCGV** [comment]
Cool. Just did that! Thanks for the suggestion.
